### PR TITLE
webimage_extra_packages for Puppeteer Headless Chrome support

### PR DESCRIPTION
**Pull request by juban**
Npm packages like codeceptjs or critical-css-webpack-plugin which depend on [Puppeteer](https://github.com/puppeteer/puppeteer/) will not be able to run from within the web container because of some missing Linux libraries.

This [Dockerfile](Dockerfile) add all required dependencies in order to run the Headless Chrome provided by Puppeteer.

### CODE REVIEW

**Comment by juban** [comment]
Hi @rfay 

I have moved the files to recipes section and removed the Debian packages already part to the Ddev web image.

**Comment by rfay** [comment]
Thanks for requesting review; sorry I haven't gotten to this, have been getting v1.14 out, hope you can try it out, https://github.com/drud/ddev/releases/tag/v1.14.0-rc2

**Comment by rfay** [comment]
Please add info to this PR on how to manually test it. You can add it to the PR or add more to the README.

**Comment by juban** [comment]
Hi @rfay 

I added a demo project in order to demonstrate the purpose of the PR.
You can test it by following the added instructions in the README.md file.
You can also comment out the `webimage_extra_packages` configuration in the config.yaml file in order to experience the missing libraires. In that case, you will get the following errors while running the `ddev yarn build` command:
```
Error: Failed to launch chrome!
error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory
```

Let me know if you feel that something is missing or not clear.

Thanks.

PS. I have tested ddev 1.14.0-rc2 and everything is running smoothly on my side. Good work, once again :)

**Comment by rfay** [comment]
Thanks so much!

**Comment by juban** [comment]
Hi @rfay,

The changes looks good to me, thank you for your review.

About the warning, it's a yarn related message and doesn't really matter.
May I ask what resulting page did you get?
If everything works fine (I just did a test from scratch and redoing the README steps), you should get something like the attached screen shot. Is that what you get?
Tailwind_Starter_Template_-_Landing_Page_Template__Tailwind_Toolbox

If you feel any clarification should be added, please let me know.

**Comment by rfay** [comment]
Here's what I see @juban , it's hard to show in screenshots, but here are the first two full screens as I scroll. Not sure how important this is.

Tailwind_Starter_Template_-_Landing_Page_Template__Tailwind_Toolbox

Tailwind_Starter_Template_-_Landing_Page_Template__Tailwind_Toolbox

**Comment by juban** [comment]
There's something wrong and what you see is the page when the related assets are missing (no CSS or JS files loaded).
Are you sure you ran the last `ddev yarn build` command?
If so, did you get any error message related to that command and are you seeing any files beside the `.gitignore` file in `demo/web/webpack-assets` folder?

**Comment by rfay** [comment]
Silly me, I did a `ddev yarn install` instead of `ddev yarn build`. It looks great now, thanks.

**Comment by juban** [comment]
Glad to hear you managed to make it work.
Thanks again for you reviews, your patience and kindness :)

**Pull request merged**
