### PR TITLE
Add Redis service and CLI command

### PR DESCRIPTION
**Pull request by gormus**

### CODE REVIEW

**Comment by rfay** [comment]
Awesome!

**Comment by dawehner** [comment]
I've just tested this PR by following the documentation in the README. It resulted into a top working redis locally. Thank you!

**Comment by Graloth** [comment]
This works without issue for me, and the added command makes working with redis in the terminal even easier.

**Comment by rfay** [comment]
@gormus looking forward to your response, thanks.

**Comment by gormus** [comment]
Sorry about the delays @rfay, I was having some unexpected conflicts on my environment.

I made the changes you requested, plus I added a new feature: 

Redis service now configurable via a `redis/redis.conf` file.

I also removed the `HTTP_EXPOSE=6379` environment variable, and the `redis-tools` web-image extra package, as they are not needed at all. Thanks for flagging them :) 

I should also mention that same configuration works for Redis 5 as well.

Please review, and let me know if you'd like any further updates.

Thanks!

**Comment by rfay** [comment]
Thanks!

**Comment by rfay** [comment]
Thanks so much for this! I tried it out (but am a novice with redis), and everybody loves it.

**Pull request merged**
