### PR TITLE
Added a Laravel recipe, fixes drud/ddev#898

### PR DESCRIPTION
**Pull request by tommym9**

### CODE REVIEW

**Comment by rfay** [comment]
You're awesome, thanks!

**Comment by rfay** [comment]
Thanks for reviewing @tomasnorre !

**Comment by tomasnorre** [comment]
You're welcome..

**Comment by rfay** [comment]
I 
* rebased this to current master
* Added a link in the top-level README
* Changed to use `ddev composer create` in the composer instructions

It worked perfectly... but I was confused by the "what next"; I imagine that I'm not the only one.

I recommend *only* providing the composer instructions, and then the artisan stuff can be removed?

And could we add a "What do I do now with that beautiful blank Laravel screen?

Screenshot_10_12_19__4_10_PM

**Comment by tomasnorre** [comment]
You start developing.. :) 

It's just a default like "Apache/Nginx" startpage to prove that the setup is working. 

If you see that screen it's working.

**Pull request merged**
