### PR TITLE
Headless Chrome service

### PR DESCRIPTION
**Pull request by isholgueras**
This is my headless chrome recipe to use along with ddev environment.

### CODE REVIEW

**Comment by rfay** [comment]
Thanks for the starter! Looking forward to some potatoes to go with the meat :)

**Comment by rfay** [comment]
Looking forward to second commit!

**Comment by rfay** [comment]
Please add your comments to this @wizonesolutions.

**Comment by rfay** [comment]
Oh still waiting for you @isholgueras and @wizonesolutions :)

**Comment by isholgueras** [comment]
What is needed to do here?

**Comment by rfay** [comment]
@isholgueras thanks for checking in. You titled  this "First commit". If it's ready, just say so and I'll give it a review. Thanks!

**Comment by rfay** [comment]
If you could suggest a simple technique for manually testing the recipe it would help me to review, also. Thanks!

**Comment by rfay** [comment]
I've been away from behat for too long, so people should improve this with PRs. Thanks!

**Pull request merged**
