### PR TITLE
Fix image names in "Using Old PHP Versions"

### PR DESCRIPTION
**Pull request by fjacobi**

### CODE REVIEW

**Comment by rfay** [comment]
Did they change how the images are tagged? I tested this originally, and those images were correct then...

**Comment by fjacobi** [comment]
I'm not really sure, but the images are named differently here. Perhaps they've streamlined them?

**Comment by rfay** [comment]
Hmm, https://hub.docker.com/r/devilbox/php-fpm-5.2 is still there and appears to be maintained... ???

**Comment by fjacobi** [comment]
Yes and if I test it today it works without any issues. 
Wonder what went wrong yesterday. /closed

**Pull request closed without merging**
