### PR TITLE
REDAXO ddev recipe

### PR DESCRIPTION
**Pull request by crydotsnake**

### CODE REVIEW

**Comment by crydotsnake** [comment]
I have to fix some issues.

**Comment by crydotsnake** [comment]
@rfay Everything should be working now! :)

**Comment by rfay** [comment]
Thanks, looking forward to trying it out! Busy week past, busy week coming, but looking forward to it!

**Comment by crydotsnake** [comment]
Okay! ^^ @rfay

**Comment by crydotsnake** [comment]
I have try it already! :).

**Comment by rfay** [comment]
Well, unless you find other reviewers, I'm the reviewer you'll get :)

**Comment by crydotsnake** [comment]
Okay! :)

**Comment by crydotsnake** [comment]
Would be cool to contribute to DDEV! :).

**Comment by rfay** [comment]
You already *are* contributing to DDEV, congrats and thanks!

**Comment by crydotsnake** [comment]
I wish i could do more! :).

**Comment by rfay** [comment]
@crydotsnake I rebased this and edited quite a bit for brevity. Your gifs were lovely but people reading this kind of a recipe just want to browse through it quickly. Please review https://github.com/drud/ddev-contrib/blob/9c0f0bc0b65a26f14b4cf00e04bb275b37301dc7/recipes/redaxo-cms/README.md and if you're good with it we'll get this pulled.

I had no trouble following your instructions and getting REDAXO going, thanks!

**Comment by crydotsnake** [comment]
@rfay It looks okay! :).

Great to hear!.

**Pull request merged**
