### PR TITLE
Adding kibana service recipe

### PR DESCRIPTION
**Pull request by alechko**
## The New Solution/Problem/Issue/Bug:

Adding Kibana service to monitor/control Elasticsearch.

## Manual Testing Instructions:

Follow the Installation section in `docker-compose-services/kibana/README.md`

### CODE REVIEW

**Comment by rfay** [comment]
Thanks for this!

**Comment by rfay** [comment]
Thanks for your work on this @alechko - Please review my commit at https://github.com/drud/ddev-contrib/pull/143/commits/a8e348c801cf4016405e03b051423f225f1a1207 

There were a number of things in all 3 of those recipes that just needed to be updated to current usage. Using the bare container name, like "elasticsearch" is ambiguous if you have more than one project running, so we've been switching per docs to the official fully-qualified name of the container, ddev-<projectname>-<service>. And using the `ports` directive actually tries to expose the ports on the host, causing conflicts between multiple projects. 

This is also rebased to upstream/master so be careful to update your fork/branch.

**Comment by alechko** [comment]
hi @rfay, I've pulled the changes and there are lots of conflicts, I'm not sure what I should do now, should I resolve the conflicts (accepting your changes) and push the updated commit?

**Comment by rfay** [comment]
Hi @alechko - `git fetch origin && git reset --hard origin/kibana` - assuming that your git remote is named "origin"

**Comment by alechko** [comment]
I've tested the updated recipe, works great and now it has https as well :)

**Comment by rfay** [comment]
Thanks so much for this contribution!

**Pull request merged**
