### PR TITLE
Symfony console support, fixes #115

### LINKED ISSUE #115: Support for Symfony console
Hi, I have created a super simple custom command to support Sympfony console by using `ddev console ...`, this makes super easy to execute Symfony console commands without ssh into the container.

I believe that other people might find it handy so I wanted to see if it's worth submitting it here as well.

Command file path:
`commands/web/console`

Command script:
```
#!/bin/bash

## Description: Run Symphony console
## Usage: console <command>
## Example: "ddev console about" or "ddev console debug:config"
bin/console $@
```

If approved, I've already forked this repo and can submit a PR.

Screen Shot 2021-01-29 at 09 59 27

### PR DESCRIPTION
**Pull request by alechko**
This adding a simple command to run Symfony console without the need to ssh into the container.

### CODE REVIEW

**Comment by rfay** [comment]
Please don't forget to add to the top-level README. Thanks!

**Comment by rfay** [comment]
Thanks for all the work on this!

**Comment by alechko** [comment]
@rfay no problem!

**Review by rfay — APPROVED** [review]
Looks good, thanks! You do know about `ddev exec` right?

**Comment by alechko** [comment]
hey @rfay , yes, I know about `ddev exec`, this is an extra shortcut around that if someone finds it useful :)

**Pull request merged**
