### PR TITLE
Add a new service with Portainer

### PR DESCRIPTION
**Pull request by davidjguru**
Sometimes, many people are not comfortable enough using the command line or just feel better using graphical user interfaces (GUIs). Due to this, the example committed here adds a new case about extending DDEV-Local networking by adding a new container for a Portainer service, the visual tool for management of containers.

### CODE REVIEW

**Comment by rfay** [comment]
Nice! 

Are you using macOS? Have you looked at the new container visualization built in to the latest (edge) docker desktop?

**Comment by rfay** [comment]
One thing I haven't every quite understood is why people need to see things at the container level like they do with portainer. Every time I fiddle with it I think "Why do I want to see the containers?". Why do you want to see the containers?

**Comment by davidjguru** [comment]
Hi @rfay,
 I'm not a macOS user, usually I'm a Linux (Ubuntu / Debian) user. I don't know how Docker Desktop, works, sorry. 
Well, the truth is I don't really need to "see" the containers. But on a daily basis, training people with a "_junior_" profile, I have observed that is more comfortable thinking in containers like items that they can "see". 

I made this case as a training tool, as a didactic resource. There're so many people with some (initial) panic over the prompt. Facilitating and gradually advancing people is part of my job. This is my context. 

Greetings, 
David.

**Comment by rfay** [comment]
In general, my goal with ddev is for people to "see" ddev, and not docker or its containers or the complexity involved there. That's why I ask. 

Of course, the need for a gui for ddev is a longstanding concern. We once had one, but it wasn't really maintainable.

**Comment by rfay** [comment]
Thanks for this!

**Pull request merged**
