### PR TITLE
WIP: Add adminer

### PR DESCRIPTION
**Pull request by bserem**
## The New Solution/Problem/Issue/Bug:
Add adminer service, see https://github.com/drud/ddev/issues/3534

## How this PR Solves The Problem:
Adds adminer as a service to ddev, allowing to manage databases with it.

## Manual Testing Instructions:

- Adminer listens to sitename.ddev.site:8080
- Username, password and dbname need to be filled by hand (`db` everywhere in ddev with mysql)

## Remaining Tasks
- [x] Add readme
- [ ] Get feedback

## Nice to have
- [ ] Allow passwordless login
- [ ] Add theme switcher plugin (need to figure out how)

### CODE REVIEW

**Comment by rfay** [comment]
Nice! I'd love it if you could implement this using https://github.com/drud/ddev-addon-template

**Comment by bserem** [comment]
I'm reading into ddev services, and I also need to figure out how to configure adminer plugins. It will take a while.

Meanwhile shall we close this PR? Since it will eventually be a service?

**Comment by rfay** [comment]
There's nothing wrong with it being here :)

**Comment by bserem** [comment]
https://github.com/bserem/ddev-adminer

I'll be glad to get some feedback and know who it works.

**Comment by rfay** [comment]
This is obsolete because [ddev get drud/ddev-adminer](https://github.com/drud/ddev-adminer) got promoted thanks to @bserem 's work. Thanks!

**Pull request closed without merging**
