### PR TITLE
[WIP] Add custom command "general_log"

### PR DESCRIPTION
**Pull request by jonaseberle**

### CODE REVIEW

**Review by rfay — CHANGES_REQUESTED** [review]
It seems like query-log would be a better name for the command than general_log?

**Comment by jonaseberle** [comment]
@rfay fine with me of course. I just chose it because the MySQL setting and feature is general_log.

**Comment by rfay** [comment]
I was just thinking about a command name that would imply it had to do with database stuff. In the context of database, general_log is explanatory, but in the context of a full web environment like ddev, it could mean so many different things.

**Comment by jonaseberle** [comment]
Name suggestion: `db-log`

[WIP] Looking into integrating slow query log

**Comment by cmuench** [comment]
> Name suggestion: `db-log`
> 
> [WIP] Looking into integrating slow query log

Why not a general "log" command with sub-commands?

Example:

`ddev log db`

Then we are able to extend the command by new loggers without a too long command list.

**Comment by jonaseberle** [comment]
@cmuench I wouldn't want to override a stock command (which is not possible btw). I think of ddev-contrib as something like Steam Greenlight where ideas can be shared and vetted. If really helpful, they might maybe eventually trigger something upstream.

**Comment by rfay** [comment]
This is a great contribution, hoping you can get back to it @jonaseberle, thanks!

**Review by rfay — APPROVED** [review]
Thanks!

**Pull request merged**
