### PR TITLE
Add support for Microsoft SQL Server

### PR DESCRIPTION
**Pull request by drupal-daffie**
## The New Solution/Problem/Issue/Bug:
Add support for the Microsoft SQL Server

## How this PR Solves The Problem:
This PR add that support

## Manual Testing Instructions:
Follow the comments in the readme file and the docker-compose file.

### CODE REVIEW

**Review by rfay — CHANGES_REQUESTED** [review]
I apologize for being so slow on this.It's a valuable contribution and I look forward to getting it in. 

* I'm not clear where the docker image is coming from. I guess not from dockerhub, but I am able to do a `docker pull` on it. But the parent repo doesn't seem to have any particular information, so makes me wonder.
* I'm pretty sure this image is amd64 only, so it won't work reliably with mac M1 or other arm64 machines. Please add that caveat in there.
* Most importantly: Installing the needed packages with post-start hooks is terribly painful and slow, please don't do that. Please change that into a .ddev/web-build/Dockerfile so it only happens once and doesn't have to be done on every `ddev start`.

I'll try to be more responsive when you update this, and I'll be happy to help you with any issues you run across getting the Dockerfile going.  But see https://ddev.readthedocs.io/en/latest/users/extend/customizing-images/#adding-extra-dockerfiles-for-webimage-and-dbimage

**Comment by drupal-daffie** [comment]
For: "I'm not clear where the docker image is coming from. I guess not from dockerhub, but I am able to do a docker pull on it. But the parent repo doesn't seem to have any particular information, so makes me wonder."
This is how Microsoft wants you to do it: "mcr.microsoft.com/mssql/server:2019-CU12-ubuntu-20.04". I have no idea how they generate the image.


For: "I'm pretty sure this image is amd64 only, so it won't work reliably with mac M1 or other arm64 machines. Please add that caveat in there." 
There is an issue open for fixing this: https://github.com/microsoft/mssql-docker/issues/734. Added comment to the MR.


For: "Most importantly: Installing the needed packages with post-start hooks is terribly painful and slow, please don't do that. Please change that into a .ddev/web-build/Dockerfile so it only happens once and doesn't have to be done on every ddev start."
I have tried that and  did not get it to work and you said: "I will be happy to help with this of course."

**Comment by rfay** [comment]
Unfortunately, it looks to me like Microsoft doesn't have msodbcsql17 or mssql-tools in their Debian 11 Bullseye repository. This is what I was working on, but got stuck with 
```
apt-get install -y msodbcsql17 mssql-tools
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package msodbcsql17
E: Unable to locate package mssql-tools
```

```Dockerfile
ARG BASE_IMAGE
FROM $BASE_IMAGE

ENV PATH="${PATH}:/opt/mssql-tools/bin"
RUN curl -sSL https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl -sSL -o /etc/apt/sources.list.d/mssql-release.list https://packages.microsoft.com/config/debian/11/prod.list

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::="--force-confold" --no-install-recommends --no-install-suggests apt-utils build-essential dialog php-pear php-dev unixodbc-dev

RUN ACCEPT_EULA=Y DEBIAN_FRONTEND=noninteractive apt-get install -y msodbcsql17 mssql-tools
RUN pecl channel-update pecl.php.net && pecl install sqlsrv && pecl install pdo_sqlsrv

RUN for v in 7.3 7.4 8.0 8.1; do \
   echo 'extension=sqlsrv.so' >> /etc/php/${v}/mods-available/sqlsrv.ini"; \
   echo 'extension=pdo_sqlsrv.so' >> /etc/php/${v}/mods-available/pdo_sqlsrv.ini" ; \
done
RUN phpenmod sqlsrv pdo_sqlsrv
```

It's easy enough to work these through one at a time just using a debian image, that's what I did. `docker run -it --rm debian:bullseye` and then work from there. 

Happy to carry on from here if you know how to get msodbcsql17 and mssql-tools on Debian 11.

**Comment by rfay** [comment]
Looks like no debian 11 yet... https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15#debian17 ?

**Comment by drupal-daffie** [comment]
Support for Debian 11 is in!

**Comment by rfay** [comment]
Yay! Hope you'll test this out

**Comment by drupal-daffie** [comment]
"Yay! Hope you'll test this out" I would very much to test it out.

**Comment by drupal-daffie** [comment]
I have placed the code from https://github.com/drud/ddev-contrib/pull/168#issuecomment-1013897055 in .ddev/web-buld/Dockerfile. After some time a got the following result:

```
daffie@daffie-MS-7395:~/Projects/ddev-93mssql$ ddev start
Starting ddev-93mssql... 
Pushed mkcert rootca certs to ddev-global-cache/mkcert 
1 error occurred: 
	* Status: The command '/bin/sh -c for v in 7.3 7.4 8.0 8.1; do    echo 'extension=sqlsrv.so' >> /etc/php/${v}/mods-available/sqlsrv.ini";    echo 'extension=pdo_sqlsrv.so' >> /etc/php/${v}/mods-available/pdo_sqlsrv.ini" ; done' returned a non-zero code: 2, Code: 2 
 
 
Failed to start ddev-93mssql: ComposeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-ddev-93mssql docker-compose -f /home/daffie/Projects/ddev-93mssql/.ddev/.ddev-docker-compose-full.yaml up --build -d', action='[up --build -d]', err='exit status 1', stdout='Sending build context to Docker daemon     831B
Step 1/15 : ARG BASE_IMAGE
Step 2/15 : FROM $BASE_IMAGE
 ---> 6fb0f2b0d779
Step 3/15 : ENV PATH="${PATH}:/opt/mssql-tools/bin"
 ---> Using cache
 ---> b6864565185b
Step 4/15 : RUN curl -sSL https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
 ---> Using cache
 ---> 6a04a99b01ed
Step 5/15 : RUN curl -sSL -o /etc/apt/sources.list.d/mssql-release.list https://packages.microsoft.com/config/debian/11/prod.list
 ---> Using cache
 ---> c4914afece2c
Step 6/15 : RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::="--force-confold" --no-install-recommends --no-install-suggests apt-utils build-essential dialog php-pear php-dev unixodbc-dev
 ---> Using cache
 ---> cfefc70bb096
Step 7/15 : RUN ACCEPT_EULA=Y DEBIAN_FRONTEND=noninteractive apt-get install -y msodbcsql17 mssql-tools
 ---> Using cache
 ---> 3735ef2ac49a
Step 8/15 : RUN pecl channel-update pecl.php.net && pecl install sqlsrv && pecl install pdo_sqlsrv
 ---> Using cache
 ---> fa34c45c2cb3
Step 9/15 : RUN for v in 7.3 7.4 8.0 8.1; do    echo 'extension=sqlsrv.so' >> /etc/php/${v}/mods-available/sqlsrv.ini";    echo 'extension=pdo_sqlsrv.so' >> /etc/php/${v}/mods-available/pdo_sqlsrv.ini" ; done
 ---> Running in 5d17f8afaac9
/bin/sh: 1: cannot create /etc/php/7.3/mods-available/sqlsrv.ini;    echo 'extension=pdo_sqlsrv.so' >> /etc/php/7.3/mods-available/pdo_sqlsrv.ini: Directory nonexistent
/bin/sh: 1: cannot create /etc/php/7.4/mods-available/sqlsrv.ini;    echo 'extension=pdo_sqlsrv.so' >> /etc/php/7.4/mods-available/pdo_sqlsrv.ini: Directory nonexistent
/bin/sh: 1: cannot create /etc/php/8.0/mods-available/sqlsrv.ini;    echo 'extension=pdo_sqlsrv.so' >> /etc/php/8.0/mods-available/pdo_sqlsrv.ini: Directory nonexistent
/bin/sh: 1: cannot create /etc/php/8.1/mods-available/sqlsrv.ini;    echo 'extension=pdo_sqlsrv.so' >> /etc/php/8.1/mods-available/pdo_sqlsrv.ini: Directory nonexistent
Sending build context to Docker daemon     490B
Step 1/6 : ARG BASE_IMAGE
Step 2/6 : FROM $BASE_IMAGE
 ---> e0b33608be1f
Step 3/6 : ARG username
 ---> Using cache
 ---> 34421e2aefb9
Step 4/6 : ARG uid
 ---> Using cache
 ---> a7896f070e78
Step 5/6 : ARG gid
 ---> Using cache
 ---> 37484c788353
Step 6/6 : RUN (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' --uid $uid "$username" || useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' "$username" || useradd  -l -m -s "/bin/bash" --gid "$gid" --comment '' "$username")
 ---> Using cache
 ---> 0eb4bba5b806
Successfully built 0eb4bba5b806
Successfully tagged drud/ddev-dbserver-mariadb-10.3:v1.18.2-ddev-93mssql-built
', stderr='1 error occurred:
	* Status: The command '/bin/sh -c for v in 7.3 7.4 8.0 8.1; do    echo 'extension=sqlsrv.so' >> /etc/php/${v}/mods-available/sqlsrv.ini";    echo 'extension=pdo_sqlsrv.so' >> /etc/php/${v}/mods-available/pdo_sqlsrv.ini" ; done' returned a non-zero code: 2, Code: 2
' 
```

**Comment by rfay** [comment]
The way to work on this is to try to do the commands manually in the web container and find out what goes wrong. 

Here it looks like there's just an error in the creation of the mode_available file.

**Comment by drupal-daffie** [comment]
@rfay: Thank you for helping me.

I have tried to debug as you have suggested. This is my dockerfile:
```
FROM debian:bullseye
ENV PATH="${PATH}:/opt/mssql-tools18/bin"
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::="--force-confold" --no-install-recommends --no-install-suggests curl gnupg2
RUN curl -sSL https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
```

This results in the following error:
```
Step 4/10 : RUN curl -sSL https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
 ---> Running in ef5065ccd8a8
curl: (77) error setting certificate verify locations:  CAfile: /etc/ssl/certs/ca-certificates.crt CApath: /etc/ssl/certs
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
gpg: no valid OpenPGP data found.
The command '/bin/sh -c curl -sSL https://packages.microsoft.com/keys/microsoft.asc | apt-key add -' returned a non-zero code: 2
```

No idea how to fix that. I have googled it, only to find very complicated stories about keyrings. I am doing something wrong and no idea what.


When I run your code in the web-build dockerfile with "ddev restart", the files sqlsrv.ini and pdo_sqlsrv.ini are not in directory mods-available/ nor in directory fpm/conf.d/. I get the idea that "debian:bullseye" is not the same as "BASE_IMAGE".

@rfay: If you could help some more that would be much appreciated.

**Comment by rfay** [comment]
So this is where you experiment with things one at a time. In fact, the link to the key provides a key, but it's apparently not a legit key for apt.

If you just do the curl, it seems to get what looks like a key:

```
# curl -sSL https://packages.microsoft.com/keys/microsoft.asc
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1.4.7 (GNU/Linux)

mQENBFYxWIwBCADAKoZhZlJxGNGWzqV+1OG1xiQeoowKhssGAKvd+buXCGISZJwT
LXZqIcIiLP7pqdcZWtE9bSc7yBY2MalDp9Liu0KekywQ6VVX1T72NPf5Ev6x6DLV
7aVWsCzUAF+eb7DC9fPuFLEdxmOEYoPjzrQ7cCnSV4JQxAqhU4T6OjbvRazGl3ag
OeizPXmRljMtUUttHQZnRhtlzkmwIrUivbfFPD+fEoHJ1+uIdfOzZX8/oKHKLe2j
H632kvsNzJFlROVvGLYAk2WRcLu+RjjggixhwiB+Mu/A8Tf4V6b+YppS44q8EvVr
M+QvY7LNSOffSO6Slsy9oisGTdfE39nC7pVRABEBAAG0N01pY3Jvc29mdCAoUmVs
ZWFzZSBzaWduaW5nKSA8Z3Bnc2VjdXJpdHlAbWljcm9zb2Z0LmNvbT6JATUEEwEC
AB8FAlYxWIwCGwMGCwkIBwMCBBUCCAMDFgIBAh4BAheAAAoJEOs+lK2+EinPGpsH
/32vKy29Hg51H9dfFJMx0/a/F+5vKeCeVqimvyTM04C+XENNuSbYZ3eRPHGHFLqe
MNGxsfb7C7ZxEeW7J/vSzRgHxm7ZvESisUYRFq2sgkJ+HFERNrqfci45bdhmrUsy
7SWw9ybxdFOkuQoyKD3tBmiGfONQMlBaOMWdAsic965rvJsd5zYaZZFI1UwTkFXV
KJt3bp3Ngn1vEYXwijGTa+FXz6GLHueJwF0I7ug34DgUkAFvAs8Hacr2DRYxL5RJ
XdNgj4Jd2/g6T9InmWT0hASljur+dJnzNiNCkbn9KbX7J/qK1IbR8y560yRmFsU+
NdCFTW7wY0Fb1fWJ+/KTsC4=
=J6gs
-----END PGP PUBLIC KEY BLOCK-----
```

Then if you try downloading the microsoft.asc and work with it manually, 
```
# curl -sSL -O https://packages.microsoft.com/keys/microsoft.asc
# apt-key add <microsoft.asc
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK
```

it actually works and adds the key. I can't guess why it's not working with it on stdin, but download the key first and then using `apt-key add` on it works, so do that as two steps. First manually, then by adding it to the Dockerfile.

And of course... take a new look at any instructions MS may have put up on how to load the key or the packages.

**Comment by drupal-daffie** [comment]
@rfay: Thank you for all your help, including with the not legit key.

I have a couple of questions:

1. My next problem is that when I build the container with `docker build .` the command `ENV PATH="${PATH}:/opt/mssql-tools/bin"` add the mssql-tools directory to the path. When I do it with `ddev restart` it does not work. Any idea why? I have kept the post start hooks for updating the path for now.

2. Is it possible to get the container build when running the command `ddev restart`? I am now unable to see why my previous problem is failing?

I have a succesful `ddev start` when I set the PHP version to 8.1. I am running out of time for the moment. I will work more on it later. I have updated MR.

**Comment by rfay** [comment]
The PATH used at build time is not the same as the PATH that gets inherited into the environment. Remind me why you have to override the PATH? There are a few ways to do it, but none elegant at this point. You can override in your `docker-compose.*.yaml` though. Are you overriding in web container or elsewhere? If https://github.com/drud/ddev/issues/3022 lands, it will make this a bit easier for web container.

I don't understand #2. The build only happens once in a project (not after every start) unless the build info changes. That's the beauty of using a Dockerfile. If you want to start over you can `ddev stop` and `docker rmi <image>-<project>-built` or `ddev delete` but ddev delete does more than you probably want.

**Comment by drupal-daffie** [comment]
About #2: When I build a container with the command `docker build .` I get a lot of information what the build is doing. When I run the command `ddev restart` I get a lot less information about how the build is doing. Is there a possibility to get more build info with the command `ddev restart`.


A also got a new problem. It is working fine when I set the `php_version` to "8.1". When I change it to "8.0" and run `ddev restart` PHP is not working any more. When I run `ddev ssh` and than `php -v` I get:
```
daffie@ddev-93mssql-web:/var/www/html/web$ php -v
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_sqlsrv.so' (tried: /usr/lib/php/20200930/pdo_sqlsrv.so (/usr/lib/php/20200930/pdo_sqlsrv.so: cannot open shared object file: No such file or directory), /usr/lib/php/20200930/pdo_sqlsrv.so.so (/usr/lib/php/20200930/pdo_sqlsrv.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'pdo_sqlsrv.so' (tried: /usr/lib/php/20200930/pdo_sqlsrv.so (/usr/lib/php/20200930/pdo_sqlsrv.so: cannot open shared object file: No such file or directory), /usr/lib/php/20200930/pdo_sqlsrv.so.so (/usr/lib/php/20200930/pdo_sqlsrv.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'sqlsrv.so' (tried: /usr/lib/php/20200930/sqlsrv.so (/usr/lib/php/20200930/sqlsrv.so: cannot open shared object file: No such file or directory), /usr/lib/php/20200930/sqlsrv.so.so (/usr/lib/php/20200930/sqlsrv.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'sqlsrv.so' (tried: /usr/lib/php/20200930/sqlsrv.so (/usr/lib/php/20200930/sqlsrv.so: cannot open shared object file: No such file or directory), /usr/lib/php/20200930/sqlsrv.so.so (/usr/lib/php/20200930/sqlsrv.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP 8.0.13 (cli) (built: Nov 22 2021 09:47:37) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.13, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.13, Copyright (c), by Zend Technologies
```

When I run `ddev ssh` and than `php-config` I get:
```
daffie@ddev-93mssql-web:/var/www/html/web$ php-config
Usage: /usr/bin/php-config [OPTION]
Options:
  --prefix            [/usr]
  --includes          [-I/usr/include/php/20210902 -I/usr/include/php/20210902/main -I/usr/include/php/20210902/TSRM -I/usr/include/php/20210902/Zend -I/usr/include/php/20210902/ext -I/usr/include/php/20210902/ext/date/lib ]
  --ldflags           [-L/usr/lib/php/20210902 ]
  --libs              [-lcrypt   -lresolv -lcrypt -lutil -lrt -lm -ldl  -lxml2 -lssl -lcrypto -lpcre2-8 -lz -lsodium -largon2 -lrt -ldl -lcrypt ]
  --extension-dir     [/usr/lib/php/20210902]
  --include-dir       [/usr/include/php/20210902]
  --man-dir           [/usr/share/man]
  --php-binary        [/usr/bin/php8.1]
  --php-sapis         [cli fpm ]
  --phpapi            [20210902]
  --ini-path          [/etc/php/8.1/cli]
  --ini-dir           [/etc/php/8.1/cli/conf.d]
  --configure-options [--includedir=/usr/include --mandir=/usr/share/man --infodir=/usr/share/info --disable-option-checking --disable-silent-rules --libdir=/usr/lib/x86_64-linux-gnu --libexecdir=/usr/lib/x86_64-linux-gnu --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --enable-cli --disable-cgi --disable-phpdbg --with-config-file-path=/etc/php/8.1/cli --with-config-file-scan-dir=/etc/php/8.1/cli/conf.d --build=x86_64-linux-gnu --host=x86_64-linux-gnu --config-cache --cache-file=/build/php8.1-8.1.3/config.cache --libdir=${prefix}/lib/php --libexecdir=${prefix}/lib/php --datadir=${prefix}/share/php/8.1 --program-suffix=8.1 --sysconfdir=/etc --localstatedir=/var --mandir=/usr/share/man --disable-all --disable-debug --disable-rpath --disable-static --with-pic --with-layout=GNU --without-pear --enable-filter --with-openssl --with-password-argon2=/usr --with-external-pcre --enable-hash --with-mhash=/usr --with-libxml --enable-session --with-sodium --with-system-tzdata --with-zlib=/usr --with-zlib-dir=/usr --enable-dtrace --enable-pcntl --with-libedit=shared,/usr build_alias=x86_64-linux-gnu host_alias=x86_64-linux-gnu CFLAGS=-g -O2 -ffile-prefix-map=/build/php8.1-8.1.3=. -fstack-protector-strong -Wformat -Werror=format-security -O2 -Wall -pedantic -fsigned-char -fno-strict-aliasing -g]
  --version           [8.1.3]
  --vernum            [80103]
```

Any idea how to fix this?

@rfay: As always thank you very much for your help. It is very much appreciated.

**Comment by rfay** [comment]
Thanks for the hard work on this. MS is not known for their Debian packaging skills, as we all know. Could you please link to their instructions on how to do the debian package installation? That will help for us to try to work with this.

**Comment by drupal-daffie** [comment]
I have created a ticket on the MS PHP driver project. 
See: https://github.com/microsoft/msphpsql/issues/1377

**Comment by rfay** [comment]
I followed up in https://github.com/microsoft/msphpsql/issues/1377 but note that the current Dockerfile you have here isn't related to their [current instructions](https://docs.microsoft.com/en-us/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-ver15#installing-on-debian). Note that packages.microsoft.com isn't being used at all any more, nothing is being installed with apt-get, it's all pecl.

**Comment by drupal-daffie** [comment]
Thank you, that is very helpful information. No more, debugging in the dark.
Also thank you you input on the MS PHP driver issue.

**Comment by rfay** [comment]
I might be wrong, but I didn't see links to the sqlsrv repo and the linux installation instructions in your readme. Please just make sure they're provided... for the future.

**Comment by drupal-daffie** [comment]
Added the 2 requested links.

**Comment by rfay** [comment]
Are you seeing a path forward on this?

**Comment by drupal-daffie** [comment]
We can do the MR with a release for PHP 8.1 only and a followup for once https://github.com/microsoft/msphpsql/issues/1377 is fixed. Or we can wait until the blocker is fixed. @rfay what do you think is best?

**Comment by rfay** [comment]
If that works for you, it's a step forward, just document that it's php8.1 only and move forward.

**Comment by truls1502** [comment]
Is it possible to have it supporting PHP 7.3?

**Comment by drupal-daffie** [comment]
User @absci has replied in https://github.com/microsoft/msphpsql/issues/1377 with how to change the used PHP version.

@rfay I have updated the Dockerfile as requested.

@truls1502: I think that you could use PHP version 7.3, but I have not tested it.

**Comment by rfay** [comment]
OK, if you're ready for this and want to bring it in and you think the README shows enough info, we can pull it. I haven't taken another look, but as much time as you've spent on it I imagine it's. I'd love to see it turned into a ddev-get add-on so it's easiest for people, but I'm not sure how much demand there is for sqlsrv, but there is some.

**Comment by drupal-daffie** [comment]
@rfay For me it is ready to be merged. Thanks for all your help with this MR.

**Comment by rfay** [comment]
Thanks, hope you'll consider converting this into a ddev-addon, https://ddev.readthedocs.io/en/latest/users/extend/additional-services/#additional-service-configurations-for-ddev - it will make it loads easier to maintain, and certainly make it available to more people.

**Comment by NickStees** [comment]
@drupal-daffie Following the current instructions in the readme.md https://github.com/drud/ddev-contrib/tree/master/docker-compose-services/sqlsrv I am getting a phpize error, Is there something maybe missing form that Readme? Only thing I deviated from was setting it to PHP7.3 but I got the same error when it was PHP 8.0

`#21 [drud/ddev-webserver:v1.20.0-inet-built 12/16] RUN pecl -d php_suffix=7.3 install sqlsrv
#21 0.514 Xdebug: [Step Debug] Time-out connecting to debugging client, waited: 200 ms. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(
#21 35.99 downloading sqlsrv-5.10.1.tgz ...
#21 35.99 Starting to download sqlsrv-5.10.1.tgz (193,661 bytes)
#21 36.03 .........................................done: 193,661 bytes
#21 36.18 34 source files, building
#21 36.18 running: phpize7.3
#21 36.18 sh: 1: phpize7.3: not found
#21 36.18 ERROR: `phpize' failed
#21 ERROR: executor failed running [/bin/sh -c pecl -d php_suffix=7.3 install sqlsrv]: exit code: 1`

**Comment by NickStees** [comment]
Got past the error by modifying line 13 of https://github.com/drud/ddev-contrib/blob/e8eb363487d764738e48fb41ee4177d473b1fd40/docker-compose-services/sqlsrv/Dockerfile#L13 to 
`RUN ACCEPT_EULA=Y DEBIAN_FRONTEND=noninteractive apt-get install -y msodbcsql18 mssql-tools php7.3-dev` adding **php7.3-dev**

**Comment by rfay** [comment]
Please do a PR @NickStees , also explain about how you did it with 7.3 in the README. Thanks!

**Comment by NickStees** [comment]
Thanks will do, I still don't have anything completely working yet, but when I do ill put it all together in a PR.

**Comment by rfay** [comment]
It would be great to see this turned into a ddev-get add-on, with configurable PHP version.

**Comment by NickStees** [comment]
@rfay Wish I knew how to make it an Add-on, yeah I was thinking why is the PHP version hard coded in that Dockerfile when I was following the readme.

**Comment by rfay** [comment]
1. Making an add-on is easy, see https://github.com/drud/ddev-addon-template
2. If you want to support multiple PHP versions (and you do) you'll have to either build them (use a for loop in the Dockerfile.sqlsrc) or you'll have to figure out if MS and company have decided to start making binary packages available. Maybe? Really? Not yet? Anyway. Or alternately, you can make a repo that builds them (for both arm64 and amd64, it's not hard) and then you can get the binary packages/tarballs from that repo in your Dockerfile. The good thing about just building it in is that your future need for maintenance is lower. The bad thing is that it already takes forever.

**Comment by seebeen** [comment]
> It would be great to see this turned into a ddev-get add-on, with configurable PHP version.

On it.

**Pull request merged**
